# Generated by Django 5.2.5 on 2025-09-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='candidate_img_available',
            field=models.BooleanField(default=True),
        ),
    ]
