# Generated by Django 5.2.5 on 2025-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_template_candidate_img_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='candidate_img_available',
            field=models.BooleanField(default=False),
        ),
    ]
