# Generated by Django 5.2.5 on 2025-09-03 19:05

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_template_candidate_img_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='candidate_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='candidates/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='preview_image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='cv-templates-images/'),
        ),
    ]
