# Generated by Django 5.2.5 on 2025-09-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_education_is_current_experience_is_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_css',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
