# Generated by Django 5.2.5 on 2025-09-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_template_template_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
